#!/bin/bash

cat <<<'
==============================================================================
Installing dependencies
==============================================================================
'
sudo pacman -S --noconfirm --needed yadm zsh lua thefuck fd fzf exa neovim \
    starship diff-so-fancy base-devel pnpm lazygit

pnpm i -g gitmoji-cli

cat <<<'
==============================================================================
Bootstrap finished
==============================================================================
'
